# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# แผนก
Department.create(id: 1 , name: "ไปรษณีย์ด่วนพิเศษ")
Department.create(id: 2 , name: "ไปรษณียภัณฑ์ลงทะเบียน")
Department.create(id: 3 , name: "ไปรษณียภัณฑ์ธรรมดา")
Department.create(id: 4 , name: "พัสดุไปรษณีย์")
Department.create(id: 5 , name: "โลจิสโพสต์")
Department.create(id: 6 , name: "ลำเลียงและขนส่ง")

# เพศ
Gender.create(id: 1 , name: "ชาย")
Gender.create(id: 2 , name: "หญิง")

# ชนิดความผิดพลาด
MistakeType.create(id: 1 , name: "พลัด")
MistakeType.create(id: 2 , name: "ขาด")
MistakeType.create(id: 3 , name: "เกิน")
MistakeType.create(id: 4 , name: "ขาด/เกิน")
MistakeType.create(id: 5 , name: "ชำรุด")
MistakeType.create(id: 6 , name: "อื่นๆ")

# การดำเนินการ
Operation.create(id: 1 , name: "รอดำเนินการ")
Operation.create(id: 2 , name: "ดำเนินการแล้ว")

# ตำแหน่ง
Position.create(id: 1 , name: 'ผู้รับจ้างทำของ')
Position.create(id: 2 , name: 'ลูกจ้าง')
Position.create(id: 3 , name: 'ลูกจ้างประจำ')
Position.create(id: 4 , name: 'พปท.1')
Position.create(id: 5 , name: 'พปท.2')
Position.create(id: 6 , name: 'พปท.3')
Position.create(id: 7 , name: 'พปท.4')
Position.create(id: 8 , name: 'พปท.5')
Position.create(id: 9 , name: 'พปท.6')
Position.create(id: 10 , name: 'พปณ.1')
Position.create(id: 11 , name: 'พปณ.2')
Position.create(id: 12 , name: 'พปณ.3')
Position.create(id: 13 , name: 'พปณ.4')
Position.create(id: 14 , name: 'พปณ.5')
Position.create(id: 15 , name: 'พปณ.6')
Position.create(id: 16 , name: 'พปณ.7')
Position.create(id: 17 , name: 'หนผ.7')
Position.create(id: 18 , name: 'หนผ.8')
Position.create(id: 19 , name: 'ผช.หน.ศป.')
Position.create(id: 20 , name: 'หน.ศป.')


# Source.create(code: , name:)
# ศูนย์ไปรษณีย์ทั้งหมด
Source.create(code: 10000 , name: 'ศูนย์ไปรษณีย์กรุงเทพ')
Source.create(code: 10001 , name: 'ศูนย์ไปรษณีย์สุวรรณภูมิ')
Source.create(code: 10010 , name: 'ศูนย์ไปรษณีย์หลักสี่')
Source.create(code: 10020 , name: 'ศูนย์ไปรษณีย์ด่วนพิเศษกรุงเทพ')
Source.create(code: 13010 , name: 'ศูนย์ไปรษณีย์พระนครศรีอยุธยา')
Source.create(code: 20010 , name: 'ศูนย์ไปรษณีย์ศรีราชา')
Source.create(code: 25010 , name: 'ศูนย์ไปรษณีย์กบินทร์บุรี')
Source.create(code: 30010 , name: 'ศูนย์ไปรษณีย์นครราชศรีมา')
Source.create(code: 34010 , name: 'ศูนย์ไปรษณีย์อุบลราชธานี')
Source.create(code: 40010 , name: 'ศูนย์ไปรษณีย์ขอนแก่น')
Source.create(code: 41010 , name: 'ศูนย์ไปรษณีย์อุดรธานี')
Source.create(code: 51010 , name: 'ศูนย์ไปรษณีย์ลำพูน')
Source.create(code: 54010 , name: 'ศูนย์ไปรษณีย์เด่นชัย')
Source.create(code: 60010 , name: 'ศูนย์ไปรษณีย์นครสวรรค์')
Source.create(code: 65010 , name: 'ศูนย์ไปรษณีย์พิษณุโลก')
Source.create(code: 70010 , name: 'ศูนย์ไปรษณีย์ราชบุรี')
Source.create(code: 80010 , name: 'ศูนย์ไปรษณีย์ทุ่งสง')
Source.create(code: 86010 , name: 'ศูนย์ไปรษณีย์ชุมพร')
Source.create(code: 90010 , name: 'ศูนย์ไปรษณีย์หาดใหญ่')


# นครสวรรค์
Source.create(code: 60000 , name: 'นครสวรรค์')
Source.create(code: 60110 , name: 'หนองบัว')
Source.create(code: 60120 , name: 'ชุมแสง')
Source.create(code: 60130 , name: 'พยุหะคีรี')
Source.create(code: 60140 , name: 'ตาคลี')
Source.create(code: 60150 , name: 'ลาดยาว')
Source.create(code: 60160 , name: 'ท่าตะโก')
Source.create(code: 60170 , name: 'โกรกพระ')
Source.create(code: 60180 , name: 'บรรพตพิสัย')
Source.create(code: 60190 , name: 'ตากฟ้า')
Source.create(code: 60210 , name: 'ช่องแค')
Source.create(code: 60220 , name: 'ไพศาลี')
Source.create(code: 60230 , name: 'เก้าเลี้ยว')
Source.create(code: 60240 , name: 'หนองเบน')
Source.create(code: 60250 , name: 'ทับกฤช')
Source.create(code: 60260 , name: 'จันเสน')

# อุทัยธานี
Source.create(code: 61000 , name: 'อุทัยธานี')
Source.create(code: 61110 , name: 'หนองฉาง')
Source.create(code: 61120 , name: 'ทัพทัน')
Source.create(code: 61130 , name: 'หนองขาหย่าง')
Source.create(code: 61140 , name: 'บ้านไร่')
Source.create(code: 61150 , name: 'สว่างอารมณ์')
Source.create(code: 61160 , name: 'ลานสัก')
Source.create(code: 61170 , name: 'เขาบางแกรก')
Source.create(code: 61180 , name: 'เมืองการุ้ง')

# กำแพงเพชร
Source.create(code: 62000 , name: 'กำแพงเพชร')
Source.create(code: 62110 , name: 'พรานกระต่าย')
Source.create(code: 62120 , name: 'คลองขลุง')
Source.create(code: 62130 , name: 'ขาณุวรลักษบุรี')
Source.create(code: 62140 , name: 'สลกบาตร')
Source.create(code: 62150 , name: 'ไทรงาม')
Source.create(code: 62160 , name: 'ปากดง')
Source.create(code: 62170 , name: 'ลานกระบือ')
Source.create(code: 62180 , name: 'คลองลาน')
Source.create(code: 62190 , name: 'ทุ่งทราย')
Source.create(code: 62210 , name: 'บึงสามัคคี')

# ตาก
Source.create(code: 63000 , name: 'ตาก')
Source.create(code: 63110 , name: 'แม่สอด')
Source.create(code: 63120 , name: 'บ้านตาก')
Source.create(code: 63130 , name: 'สามเงา')
Source.create(code: 63140 , name: 'แม่ระมาด')
Source.create(code: 63150 , name: 'ท่าสองยาง')
Source.create(code: 63160 , name: 'พบพระ')
Source.create(code: 63170 , name: 'อุ้มผาง')

# ปจ
Source.create(code: 13000 , name: 'พระนครศรีอยุธยา')
Source.create(code: 14000 , name: 'อ่างทอง')
Source.create(code: 15000 , name: 'ลพบุรี')
Source.create(code: 16000 , name: 'สิงห์บุรี')
Source.create(code: 17000 , name: 'ชัยนาท')
Source.create(code: 18000 , name: 'สระบุรี')
Source.create(code: 20000 , name:'ชลบุรี')
Source.create(code: 21000 , name: 'ระยอง')
Source.create(code: 22000 , name: 'จันทบุรี')
Source.create(code: 23000 , name: 'ตราด')
Source.create(code: 24000 , name: 'ฉะเชิงเทรา')
Source.create(code: 25000 , name: 'ปราจีนบุรี')
Source.create(code: 26000 , name: 'นครนายก')
Source.create(code: 27000 , name: 'สระแก้ว')
Source.create(code: 30000 , name: 'นครราชศรีมา')
Source.create(code: 31000 , name: 'บุรีรัมท์')
Source.create(code: 32000 , name: 'สุรินทร์')
Source.create(code: 33000 , name: 'ศรีสะเกษ')
Source.create(code: 34000 , name: 'อุบลราชธานี')
Source.create(code: 35000 , name: 'ยโสธร')
Source.create(code: 36000 , name: 'ชัยภูมิ')
Source.create(code: 37000 , name: 'อำนาจเจริญ')
Source.create(code: 38000 , name: 'บึงกาฬ')
Source.create(code: 39000 , name: 'หนองบัวลำภู')
Source.create(code: 40000 , name: 'ขอนแก่น')
Source.create(code: 41000 , name: 'อุดรธานี')
Source.create(code: 42000 , name: 'เลย')
Source.create(code: 43000 , name: 'หนองคาย')
Source.create(code: 44000 , name: 'มหาสารคาม')
Source.create(code: 45000 , name: 'ร้อยเอ็ด')
Source.create(code: 46000 , name: 'กาฬสินธุ์')
Source.create(code: 47000 , name: 'สกลนคร')
Source.create(code: 48000 , name: 'นครพนม')
Source.create(code: 49000 , name: 'มุกดาหาร')
Source.create(code: 50000 , name: 'เชียงใหม่')
Source.create(code: 51000 , name: 'ลำพูน')
Source.create(code: 52000 , name: 'ลำปาง')
Source.create(code: 53000 , name: 'อุตรดิตถ์')
Source.create(code: 54000 , name: 'แพร่')
Source.create(code: 55000 , name: 'น่าน')
Source.create(code: 56000 , name: 'พะเยา')
Source.create(code: 57000 , name: 'เชียงราย')
Source.create(code: 64000 , name: 'สุโขทัย')
Source.create(code: 65000 , name: 'พิษณุโลก')
Source.create(code: 66000 , name: 'พิจิตร')
Source.create(code: 67000 , name: 'เพชรบูรณ์')
Source.create(code: 70000 , name: 'ราชบุรี')
Source.create(code: 71000 , name: 'กาญจนบุรี')
Source.create(code: 72000 , name: 'สุพรรณบุรี')
Source.create(code: 73000 , name: 'นครปฐม')
Source.create(code: 74000 , name: 'สมุทรสาคร')
Source.create(code: 75000 , name: 'สมุทรสงคราม')
Source.create(code: 76000 , name: 'เพชรบุรี')
Source.create(code: 77000 , name: 'ประจวบคีรีขันธ์')
Source.create(code: 80000 , name: 'นครศรีธรรมราช')
Source.create(code: 81000 , name: 'กระบี่')
Source.create(code: 82000 , name: 'พังงา')
Source.create(code: 83000 , name: 'ภูเก็ต')
Source.create(code: 84000 , name: 'สุราษฏร์ธานี')
Source.create(code: 85000 , name: 'ระนอง')
Source.create(code: 86000 , name: 'ชุมพร')
Source.create(code: 90000 , name: 'สงขลา')
Source.create(code: 91000 , name: 'สตูล')
Source.create(code: 92000 , name: 'ตรัง')
Source.create(code: 93000 , name: 'พัทลุง')
Source.create(code: 94000 , name: 'ปัตตานี')
Source.create(code: 95000 , name:' ยะลา')
Source.create(code: 96000 , name: 'นราธิวาส')
